### ISSUE TITLE
Unable to send notification to ALL with data

### ISSUE THREAD

**Issue by k1115** [Lanseuo/onesignal-notifications#5]
notification_to_all_users = SegmentNotification(
        contents={
            "en": body
        },
        included_segments=SegmentNotification.ALL,
        data={}
    )
    client.send(notification_to_all_users)

This code is not working.
If I change ALL to ACTIVE_UESRS, then it works.
Please help me to resolve this issue.

**Comment by LucasHild** [comment]
Sorry, for the late response. Can you please specify "this code is not working"? Does the code throw an error?

Please send me the output of

```python
result = client.send(notification_to_all_users)
print(result)
```

Thanks!

**Comment by Suryanandsingh** [comment]
Hi,
I'm facing with the same problem.
@Lanseuo, result output is:
**{'id': '', 'recipients': 0, 'errors': ['All included players are not subscribed']}**

Thanks

**Comment by LucasHild** [comment]
This issue is related to OneSignal and is not caused by the library. The error message "All included players are not subscribed" usually means that there is no user in this segment.
If you want to have an overview of all the available segments for your app with the amount of subscribed users, you can go to https://app.onesignal.com/apps/YOUR-APP-ID/segments and have a look there.
